name: Sync to GitLab

on:
    push:
        branches:
            - main

jobs:
    sync-to-gitlab:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
                uses: actions/checkout@v4

            - name: Mirror to GitLab
                env:
                    GITLAB_URL: ${{ secrets.GITLAB_URL }}
                    GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
                    GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
                run: |
                    git config --global user.name "${GITLAB_USERNAME}"
                    git config --global user.email "github-actions@users.noreply.github.com"
                    git remote add gitlab "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${GITLAB_URL}"
                    git push --mirror gitlab